defaults: &defaults
  adapter: mysql2
  username: root
  password: 5tekapU3
  pool: 5
  encoding: utf8
  reconnect: false
  host: localhost

development:
  <<: *defaults
  database: zinmatics_development

test:
  <<: *defaults
  database: zinmatics_test
